name: Fuse App For Windows
run-name: Build Fuse App for Windows / ${{ github.actor }} /

# Executed upon each commit pushed, merge commit in PR
on: [push, pull_request]

jobs:
  libspectrum:
    # Reuse libspectrum's build wokflow and artefact
    name: "Libspectrum lib (Windows)"
    uses: arki55/fuse-libspectrum/.github/workflows/build_windows.yml@arki55/features/T9-github-build-checks-libspectrum
    with:
      branch: arki55/features/T9-github-build-checks-libspectrum
      # repo name is taken from var.LIBSPECTRUM_REPO

########################################
### SUPPORTED Windows configurations ###
########################################

  # Win32 / 1
  win32-default:
    name: "Fuse Win32 UI + libxml2 (Windows)"
    needs: [libspectrum]
    uses: ./.github/workflows/_build_windows_sub.yml
    with:
      dependencies: "--with-win32"
      configure_params: ""
      verify_ui: "win32"
      verify_libxml2: "yes"
      verify_audio: "directsound"

  # Win32 / 2
  win32-no-libxml2:
    name: "Fuse Win32 UI w/o libxml2 (Windows)"
    needs: [libspectrum]
    uses: ./.github/workflows/_build_windows_sub.yml
    with:
      dependencies: ""
      configure_params: "--with-win32 --without-libxml2"
      verify_ui: "win32"
      verify_libxml2: "no"
      verify_audio: "directsound"

  # Win32 / 3
  win32-no-libxml2:
    name: "Fuse Win32 UI + win32sound (Windows)"
    needs: [libspectrum]
    uses: ./.github/workflows/_build_windows_sub.yml
    with:
      dependencies: ""
      configure_params: "--with-win32 --with-audio-driver=win32sound"
      verify_ui: "win32"
      verify_libxml2: "no"
      verify_audio: "win32sound"

  # Win32 / 4
  win32-no-libxml2:
    name: "Fuse Win32 UI + null sound (Windows)"
    needs: [libspectrum]
    uses: ./.github/workflows/_build_windows_sub.yml
    with:
      dependencies: ""
      configure_params: "--with-win32 --with-audio-driver=null"
      verify_ui: "win32"
      verify_libxml2: "no"
      verify_audio: "null"
