name: Fuse App For Linux (Default)
run-name: Build Fuse App for Linux (Default) / ${{ github.actor }} /
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: (1) Install dependencies
        run: |
          echo "No installable dependencies"

      - name: (2) Build and install libspectrum
        uses: arki55/fuse-libspectrum/.github/workflows/build_linux.yml@arki55/features/T9-github-build-checks-libspectrum
        with:
          path: libspectrum-master
          branch: master
          repo: ${{ env.LIBSPECTRUM_REPO }}

      - name: (3) Check out repository code
        uses: actions/checkout@v3

      - name: (4) Autogen.sh
        run: ./autogen.sh

      - name: (5) Configure for linux
        run: ./configure

      - name: (6) Make
        run: make

      - name: (7) Install
        run: sudo make install

      - name: (8) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
