name: Fuse App For Windows
run-name: Build Fuse App for Windows / ${{ github.actor }} /

# Executed upon each commit pushed, merge commit in PR
on: [push, pull_request]

jobs:
  libspectrum:
    # Reuse libspectrum's build wokflow and artefact
    name: "Libspectrum lib (Windows)"
    uses: arki55/fuse-libspectrum/.github/workflows/build_windows.yml@arki55/features/T9-github-build-checks-libspectrum
    with:
      branch: arki55/features/T9-github-build-checks-libspectrum
      # repo name is taken from var.LIBSPECTRUM_REPO

########################################
### SUPPORTED Windows configurations ###
########################################

  # Win32 UI
  win32-ui:
    name: "Fuse Win32 UI (Windows)"
    needs: [libspectrum]
    uses: ./.github/workflows/_build_windows_sub.yml
    with:
      name: "WIN32 UI"
      dependencies: ""
      configure_params: "--with-win32"
      verify_ui: "win32"
