name: Fuse App WII Build
run-name: Build Fuse App for WII / ${{ github.actor }} /
on: [push]
jobs:
  build:
    name: Build Fuse App for WII
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc
    steps:
      - name: (1) Check out repository code
        uses: actions/checkout@v3

      - name: (2) Install dependencies
        run: |
          echo "Installing dependencies .."
          echo "Using devkitpro/devkitppc image, all should be set up."

      - name: (3) Autogen.sh
        run: |
          echo "(not) Running autogen.sh .."

      - name: (4) Configure for WII
        run: |
          echo "Running configure for WII .."
          ./configure --target=powerpc-gekko --host=powerpc-gekko \
            --prefix=$DEVKITPPC \
            --with-wii

      - name: (5) Make
        run: |
          echo "Running make .."
          make

      - name: (6) Install (+sudo)
        run: |
          echo "Running make install .."
          sudo make install

      - name: (7) Finish
        run: |
          echo "🍏 Finishing with status ${{ job.status }}."
