name: Fuse App For WII
run-name: Build Fuse App for WII / ${{ github.actor }} /

# Executed upon each commit pushed, merge commit in PR
on: [push, pull_request]

jobs:
  libspectrum:
    # Reuse libspectrum's build wokflow and artefact
    # Only one case possible - without any libs, fake glib
    name: "Libspectrum lib (WII)"
    uses: arki55/fuse-libspectrum/.github/workflows/build_wii_sub.yml@arki55/github-workflows
    with:
      branch: arki55/github-workflows
      key: fuse-app
      use_zlib: false
      use_bzip2: false
      use_libgcrypt: false
      use_libaudiofile: false
      use_fake_glib: true
      # repo name is taken from var.LIBSPECTRUM_REPO

#########################################
### SUPPORTED WII UI configurations ###
#########################################

  # Default build without any configure params (xlib)
  default-ui:
    name: "Fuse Default UI (WII)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_wii_sub.yml
    with:
      name: Default
      dependencies: ""
      configure_params: ""
      verify_ui: "xlib"
      verify_audio: "oss"

  # NULL UI + sound
  null-ui:
    name: "Fuse NULL UI (WII)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_wii_sub.yml
    with:
      name: "NULL UI"
      dependencies: ""
      configure_params: "--with-null-ui"
      verify_ui: "null"
      verify_audio: "null"

  # WII UI
  wii-ui:
    name: "Fuse WII UI (WII)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_wii_sub.yml
    with:
      name: GTK3 UI
      dependencies: ""
      configure_params: "--with-wii-ui"
      verify_ui: "wii"
      verify_audio: "oss"
