name: Deploy Fuse App For Windows
run-name: Deploy Fuse App for Windows / ${{ github.actor }} /

# Executed upon manual request
on: [workflow_dispatch, push]

jobs:
########################################
###  Make dependecies (Libspectrum)  ###
########################################
  libspectrum:
    # Reuse libspectrum's build wokflow and artefact (all libs enabled, fake glib)
    name: "Libspectrum lib (Windows)"
    uses: arki55/fuse-libspectrum/.github/workflows/build_windows_sub.yml@arki55/github-workflows
    with:
      branch: arki55/github-workflows
      key: fuse-app
      # repo name is taken from var.LIBSPECTRUM_REPO

########################################
### Make Testing builds for Windows  ###
########################################

  # Win32 / 1 (Build)
  build-win32-ui-default:
    name: "Fuse Win32 UI + libxml2 (Windows)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_windows_sub.yml
    with:
      key: "win32-ui-default"
      dependencies: "mingw64-i686-libxml2"
      configure_params: |
        --with-win32 \
        --with-test-build='Reason: ${{ inputs.reason }}\\nTriggered by: ${{ github.actor }}\\nBranch: ${{ github.ref_name }}\\nDate: #NOW#'
      verify_ui: "win32"
      verify_libxml2: "yes"
      verify_audio: "directsound"
      upload_artifacts: true

  # SDL / 1 (Build)
  build-sdl-ui-sdl-sound:
    name: "Fuse SDL 1 UI + sound (Windows)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_windows_sub.yml
    with:
      key: "sdl1-ui-sdl1-sound"
      dependencies: "mingw64-i686-SDL"
      configure_params: |
        --without-win32 --with-sdl --disable-sdl2 --with-audio-driver=sdl \
        --with-test-build='Reason: ${{ inputs.reason }}\\nTriggered by: ${{ github.actor }}\\nBranch: ${{ github.ref_name }}\\nDate: #NOW#'
      verify_ui: "sdl"
      verify_libxml2: "no"
      verify_audio: "sdl"
      verify_other: "Using SDL 2: no"
      upload_artifacts: true

########################################
###     Deploy Testing build(s)      ###
########################################

  # Win32 / 1 (Deploy)
  deploy-win32-ui-default:
    name: "Deploy ZIP to FTP"
    needs: [build-win32-ui-default]
    uses: ./.github/workflows/deploy_build.yml@arki55/features/T13-github-distribution-workflow
    with:
      artefact: fuse-windows-win32-ui-default
      deploy_zip: true
      deploy_sha1: false

  # SDL / 1 (Deploy)
  deploy-sdl-ui-sdl-sound:
    name: "Deploy ZIP to FTP"
    needs: [build-sdl-ui-sdl-sound]
    uses: ./.github/workflows/deploy_build.yml@arki55/features/T13-github-distribution-workflow
    with:
      artefact: fuse-windows-sdl-ui-sdl-sound
      deploy_zip: true
      deploy_sha1: false
