name: Nightly build
run-name: Automated nightly build and pre-release

# Executed every night (1 AM) + button
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  # Merge master from defined repo (usually official fuse repo)
  catchup:
    name: "Merge foreign master"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --prune
      - run: git remote add repo ${{ vars.PARENT_FUSE_REPO }}
      - run: git fetch repo
      - run: git merge repo/${{ vars.PARENT_FUSE_BRANCH }}
      - run: git push

  # Build and release nightly prerelease version from master (no draft)
  master:
    needs: [catchup]
    name: "Nightly build from master"
    uses: ./.github/workflows/test_release.yml
    with:
      reason: "Nightly master build"
      draft: false
      generateReleaseNotes: true
      libspectrum_branch: "master"
    secrets:
      RELEASE_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
