name: Nightly build
run-name: Automated nightly build and pre-release

# Executed every night (1 AM) + button
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      force_build:
        type: boolean
        required: false
        default: false
        description: "Force build even if the branch was not updated with master branch from parent repo. Defaults to false."

jobs:

  # Build and release nightly prerelease version from master (no draft).
  # Use APPEND build type, appending date and branch from last git entry, 
  #   keep latest 5 releases, cancel release build if nothing to be merged.
  master:
    name: "Nightly build from master"
    uses: ./.github/workflows/test_release.yml
    with:
      reason: "Nightly master build"
      draft: false
      generateReleaseNotes: true
      libspectrum_branch: "master"
      fuse_version_pattern: "<ver>-<ref>-<log_date>"
      tag_pattern: "nightly-<ver>-<ref>-<log_date>"
      keep_latest: 5
      build_type: "STD"
      merge_master: true
      merge_master_cancel: ${{ inputs.force_build == false }}
    secrets:
      RELEASE_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
    permissions:
      contents: write
