name: Nightly build
run-name: Automated nightly build and pre-release

# Executed every night (1 AM) + button
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  # Build and release nightly prerelease version from master (no draft)
  master:
    name: "Nightly build from master"
    uses: ./.github/workflows/test_release.yml
    with:
      reason: "Nightly master build"
      draft: false
      generateReleaseNotes: true
      libspectrum_branch: "master"
    secrets:
      RELEASE_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
