name: Automated testing build
run-name: Automated build and pre-release for arki55/testing branch

# Executed on every push to this branch
on:
  push:
    branches: [ arki55/testing ]
  workflow_dispatch:

jobs:

  # Build and release prerelease version from arki55/testing (no draft).
  # Use STD build type, appending date and branch from last git entry, 
  #   keep latest 5 releases
  testing:
    name: "Automated build from arki55/testing"
    uses: ./.github/workflows/test_release.yml
    with:
      reason: "Automated build from arki55/testing"
      draft: false
      generateReleaseNotes: true
      libspectrum_branch: "arki55/testing"
      fuse_version_pattern: "<ver>-<ref>-<log_date>"
      tag_pattern: "fuse-<ver>-<ref>-<log_date>"
      keep_latest: 5
      build_type: "STD"
      merge_master: false
      merge_master_cancel: false
    secrets:
      RELEASE_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
      LIBSPECTRUM_TOKEN: "${{ secrets.LIBSPECTRUM_TOKEN }}"
    permissions:
        contents: write
