name: Test version of Fuse App
run-name: Build & Deploy Test version of Fuse App / ${{ github.actor }} /

# Executed upon manual request
on: [workflow_dispatch, push]

jobs:

  ########################################
  ###  Make dependecies (Libspectrum)  ###
  ########################################

  libspectrum-windows:
    # Reuse libspectrum's build wokflow and artefact (all libs enabled, fake glib)
    name: "Libspectrum lib"
    uses: arki55/fuse-libspectrum/.github/workflows/build_windows_sub.yml@arki55/github-workflows
    with:
      branch: arki55/github-workflows
      key: fuse-app
      # repo name is taken from var.LIBSPECTRUM_REPO

  ########################################
  ### Make Testing builds for Windows  ###
  ########################################

  # Win32 UI
  build-win32-ui-default:
    name: "Fuse Win32 UI"
    needs: [libspectrum-windows]
    uses: ./.github/workflows/test_release_windows_sub.yml
    with:
      reason: "aaaa"
      key: "win32-ui-default"
      dependencies: ""
      configure_params: "--with-win32"
      verify_ui: "win32"
      verify_audio: "directsound"
    secrets:
      DEPLOY_ZIP_PATH: "${{ secrets.DEPLOY_ZIP_PATH }}"
      DEPLOY_ZIP_HOST: "${{ secrets.DEPLOY_ZIP_HOST }}"
      DEPLOY_ZIP_USER: "${{ secrets.DEPLOY_ZIP_USER }}"
      DEPLOY_ZIP_PASS: "${{ secrets.DEPLOY_ZIP_PASS }}"

  # SDL1 UI+sound
  build-sdl-ui-sdl-sound:
    name: "Fuse SDL1 (UI + sound)"
    needs: [libspectrum-windows]
    uses: ./.github/workflows/test_release_windows_sub.yml
    with:
      reason: "bbbb"
      key: "sdl1-ui-sdl1-sound"
      dependencies: "mingw64-i686-SDL"
      configure_params: "--without-win32 --with-sdl --disable-sdl2 --with-audio-driver=sdl"
      verify_ui: "sdl"
      verify_audio: "sdl"
      verify_other: "Using SDL 2: no"
    secrets:
      DEPLOY_ZIP_PATH: "${{ secrets.DEPLOY_ZIP_PATH }}"
      DEPLOY_ZIP_HOST: "${{ secrets.DEPLOY_ZIP_HOST }}"
      DEPLOY_ZIP_USER: "${{ secrets.DEPLOY_ZIP_USER }}"
      DEPLOY_ZIP_PASS: "${{ secrets.DEPLOY_ZIP_PASS }}"

  ########################################
  ### Create release, attach ZIP files ###
  ########################################

  release:
    name: "Create Testing release"
    needs:
      - build-win32-ui-default
      - build-sdl-ui-sdl-sound
    runs-on: ubuntu-latest
    steps:
      # Prepare friendly tag name ( slashes => _ )
      - name: (1) Prepare variables
        id: prep
        run: |
          ref_name="${{ github.ref_name }}"
          use_tag="test_${ref_name//\//_}"
          echo "Tag name: ${use_tag}"
          echo "use_tag=${use_tag}" >> "$GITHUB_OUTPUT"

      - name: (2) Download all generated files
        uses: actions/download-artifact@v3

      - name: (3) Created release with zip files
        uses: ncipollo/release-action@v1
        with:
          name: "Test build for ${{ github.ref_name }}"
          # Attach all generated build zips
          artifacts: "*/*.zip"
          # determines structure of files in Source Forge
          tag: "${{ steps.prep.outputs.use_tag }}"
          # Is not an official release
          prerelease: true
          # Needs to be published manually
          draft: true
          # linked to a branch/pull request
          commit: ${{ github.ref_name }}
          # Special permissions needed
          token: "${{ secrets.RELEASE_TOKEN }}"
