# Reusable workflow for creating test release (Windows builds)
name: Test version of Fuse App (Windows)
run-name: Build & Deploy Test version of Fuse App For Windows / ${{ github.actor }} /

on:
  workflow_call:
    inputs:
      # Description of this test build
      reason:
        type: string
        required: true
      # Build parameters (forwarded)
      key:
        type: string
        required: true
      dependencies:
        type: string
        required: false
      configure_params:
        type: string
        required: true
      verify_ui:
        type: string
        required: true
      verify_audio:
        type: string
        required: true
      verify_other:
        type: string
        required: false
    secrets:
      # Deployment secrets (FTP access)
      DEPLOY_ZIP_PATH:
        description: "Relative path that prefixes uploaded ZIP file on FTP server"
        required: true
      DEPLOY_ZIP_HOST:
        description: "Hostname of FTP server where ZIP package will be uploaded"
        required: true
      DEPLOY_ZIP_USER:
        description: "Username that will be used for uploading ZIP file to FTP server"
        required: true
      DEPLOY_ZIP_PASS:
        description: "Password for user that will be used for uploading ZIP package to FTP server"
        required: true
    
jobs:

  # Build Fuse App
  build:
    name: "Build Fuse"
    uses: ./.github/workflows/build_windows_sub.yml
    with:
      key: "${{ inputs.key }}"
      dependencies: "${{ inputs.dependencies }}"
      configure_params: "${{ inputs.configure_params }} --with-test-build='Reason: ${{ inputs.reason }}\\nTriggered by: ${{ github.actor }}\\nBranch: ${{ github.ref_name }}\\nDate: #NOW#'"
      verify_ui: "${{ inputs.verify_ui }}"
      verify_audio: "${{ inputs.verify_audio }}"
      upload_artifacts: true

###  # Win32 / 1 (Deploy)
###  deploy:
###    name: "Deploy ZIP"
###    needs: [build]
###    uses: ./.github/workflows/deploy_build_sub.yml
###    with:
###      artefact: "fuse-windows-${{ inputs.key }}"
###      deploy_zip: true
###      deploy_sha1: false
###    secrets:
###      DEPLOY_ZIP_PATH: "${{ secrets.DEPLOY_ZIP_PATH }}"
###      DEPLOY_ZIP_HOST: "${{ secrets.DEPLOY_ZIP_HOST }}"
###      DEPLOY_ZIP_USER: "${{ secrets.DEPLOY_ZIP_USER }}"
###      DEPLOY_ZIP_PASS: "${{ secrets.DEPLOY_ZIP_PASS }}"
